### ISSUE TITLE
use of undeclared identifier 'close' / 'select'

### ISSUE THREAD

**Issue by nvowell** [MultiplayerBook/MultiplayerBook#5]
Hi, I've downloaded the example code and attempted to compile on OSX with Xcode 7.3 and I get these same errors for the examples in every chapter. I can't find them defined anywhere. Am I missing something?

**Comment by chalonverse** [comment]
It seems like Xcode 7.3 changed something with how either the unistd.h header is included, or the way implicit definition of libc functions was handled.

Anyway, I have just pushed a commit that fixes the code compiling on Xcode 7.3 for me. There are several warnings, but it at least seems to compile/run as far as I can tell.

https://github.com/MultiplayerBook/MultiplayerBook/commit/fe9d9f43f82e5bb8a4b4ceb8f92817bb46608cb7
